apiVersion: v1
kind: Service
metadata:
  name: cv-service
  namespace: default
  labels:
    app: cv
spec:
  type: NodePort
  selector:
    app: cv
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30085

